[BF-92][BF-96] Implement update news and about us logic
STA-Development/BEP_FE pull request #103
Opened 2023-06-06 16:13 UTC by alexkocharyan01

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-06-06 16:58 UTC, ArthurO2002 requested changes

2023-06-06 16:58 UTC, ArthurO2002 commented on src/components/AboutUs/AboutUsForm/AboutUsForm.tsx
> +import { useImageUpload } from '../../../hooks/ImageUpload'
```suggestion
import { useImageUpload } from '@hooks/ImageUpload'
```

2023-06-12 09:45 UTC, alexkocharyan01 commented on src/components/AboutUs/AboutUsForm/AboutUsForm.tsx
> +import { useImageUpload } from '../../../hooks/ImageUpload'
done

2023-06-12 16:09 UTC, ArthurO2002 requested changes

2023-06-12 16:09 UTC, ArthurO2002 commented on src/components/AboutUs/AddMember/AboutUsMember.tsx
> +  imageURL: null ?? '',
What does this mean :)
It's always ''

2023-06-12 16:19 UTC, alexkocharyan01 commented on src/components/AboutUs/AddMember/AboutUsMember.tsx
> +  imageURL: null ?? '',
done

2023-06-12 17:23 UTC, ArthurO2002 approved these changes

2023-06-12 17:24 UTC, merged