Change contact us form default values, fix warning
STA-Development/BEP_FE pull request #109
Opened 2023-06-13 14:34 UTC by alexkocharyan01

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-06-15 14:23 UTC, ArthurO2002 requested changes

2023-06-15 14:23 UTC, ArthurO2002 commented on next.config.js
> +  reactStrictMode: false,
don't push this)

2023-06-16 12:01 UTC, alexkocharyan01 commented on src/constants/contactUs.ts
> +export const phoneRegex = /^\+[\d]+$/
for phone number, in first must be +

2023-06-16 12:01 UTC, alexkocharyan01 commented on next.config.js
> +  reactStrictMode: false,
done

2023-06-16 19:20 UTC, ArthurO2002 approved these changes

2023-06-19 12:22 UTC, merged