fix/Admin should not have access to Settings and Applications
STA-Development/BEP_FE pull request #114
Opened 2023-06-20 13:11 UTC by DavMovsesyan2002

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-06-20 13:41 UTC, Arthur02V requested changes

2023-06-20 13:41 UTC, Arthur02V commented on src/pages/index.tsx
> +  const isAdmin = () => {
Rename to `startNowUrl`

2023-06-20 13:41 UTC, Arthur02V commented on src/Middleware.tsx
>      }
Check if this is needed, if no please remove

2023-06-21 08:36 UTC, ArthurO2002 approved these changes

2023-06-21 08:36 UTC, merged