FEAT: Implement redux and modals controller
STA-Development/BEP_FE pull request #12
Opened 2023-03-28 22:51 UTC by gor017

### What are you trying to accomplish?
[BF-3]
[BF-12]
### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-03-28 22:53 UTC, ArthurO2002 requested changes

2023-03-28 22:53 UTC, ArthurO2002 commented on src/pages/profile/applications/index.tsx
> +              )
Move to function

2023-03-28 22:53 UTC, ArthurO2002 commented on src/pages/profile/applications/index.tsx
> +      }
move

2023-03-28 23:00 UTC, gor017 commented on src/pages/profile/applications/index.tsx
> +              )
Done

2023-03-28 23:09 UTC, Antonyan7 approved these changes

2023-03-28 23:09 UTC, Antonyan7 commented on src/pages/_app.tsx
> +            <ChildLayout>
HierarchicalLayout

2023-03-29 12:42 UTC, rikarsen requested changes

2023-03-29 12:42 UTC, rikarsen commented on src/components/Modals/Application/AddApplicationModal/index.tsx
> +  variable: '--font-roboto',
also this

2023-03-30 18:11 UTC, gor017 commented on src/components/Modals/Application/AddApplicationModal/index.tsx
> +    <Dialog
https://beparmenia.atlassian.net/jira/software/c/projects/BF/boards/1?modal=detail&selectedIssue=BF-23&assignee=61b21390ef18ca0071f96582

2023-03-30 18:16 UTC, gor017 commented on package.json
> +    "@types/react-redux": "^7.1.25",
Done

2023-03-30 18:16 UTC, gor017 commented on src/pages/_app.tsx
> +            <ChildLayout>
Done

2023-03-30 18:16 UTC, gor017 commented on src/components/Modals/Application/AddApplicationModal/index.tsx
> +    <Dialog
Done

2023-03-30 19:32 UTC, rikarsen approved these changes

2023-03-30 19:32 UTC, rikarsen commented on src/components/Modals/Application/AddApplicationModal/index.tsx
> +const roboto = Roboto({
https://beparmenia.atlassian.net/browse/BF-29

2023-03-31 05:09 UTC, merged