FEAT: Events Page
STA-Development/BEP_FE pull request #21
Opened 2023-04-03 11:32 UTC by alexkocharyan01

2023-04-03 12:07 UTC, DavGalstyan98 commented on src/pages/events/index.tsx
> +                  {showMore && item.id === showModeId ? (
I think you can have 1 button and check classNames and Text inside button component

2023-04-03 15:00 UTC, rikarsen commented on src/pages/events/index.tsx
> +            className="hover:rounded-2.5 mt-5 flex flex-col rounded border border-gray-thin p-5 hover:border-primary xl:mt-[60px] xl:flex-row xl:items-start xl:justify-between"
xl:mt-15

2023-04-03 15:00 UTC, rikarsen commented on src/pages/events/index.tsx
> +                    className={`hidden pl-0  xl:mt-[30px] xl:flex ${
xl:mt-7.5

2023-04-03 15:19 UTC, Arthur02V requested changes

2023-04-03 15:19 UTC, Arthur02V commented on src/pages/events/index.tsx
> +            <div className="xl:w-[500px]">
maybe max-width

2023-04-03 15:19 UTC, Arthur02V commented on src/pages/events/index.tsx
> +                      onClick={() => setShowModeId(0)}
Id 0 can be a thing null should be the value

2023-04-03 15:28 UTC, rikarsen commented on src/pages/events/index.tsx
> +        <div className="mt-5 flex w-full justify-between border-b border-gray-thin pb-5 xl:pb-10">
and add description inside PageHeader component with condition

2023-04-03 15:30 UTC, rikarsen commented on src/pages/events/index.tsx
> +                    onClick={() => setShowModeId(0)}
null instead of 0

2023-04-03 16:13 UTC, ArthurO2002 submitted a review, later dismissed

2023-04-03 17:36 UTC, ArthurO2002 approved these changes

2023-04-03 18:24 UTC, ArthurO2002 commented on src/pages/events/index.tsx
> +                {item.id === showModeId ? item.info : `${item.info.substring(0, 130)}`}
add todo to change later

2023-04-04 15:49 UTC, rikarsen approved these changes

2023-04-04 15:49 UTC, merged