FEAT:Monitoring System Page
STA-Development/BEP_FE pull request #22
Opened 2023-04-03 15:10 UTC by DavMovsesyan2002

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-04-03 15:23 UTC, ArthurO2002 requested changes

2023-04-03 15:23 UTC, ArthurO2002 commented on src/components/OrDivider/Divider.tsx
> +)
Can we use OrDivider component with condition that will remove `or`

2023-04-03 15:23 UTC, ArthurO2002 commented on src/components/OrDivider/Divider.tsx
> +)
Rename that component to `Divider`

2023-04-03 15:23 UTC, ArthurO2002 commented on src/pages/monitoring-systems/index.tsx
> +        </Button>
Button should not be there

2023-04-03 18:49 UTC, ArthurO2002 approved these changes

2023-04-03 18:56 UTC, gor017 submitted a review, later dismissed

2023-04-03 19:00 UTC, rikarsen requested changes

2023-04-03 19:00 UTC, rikarsen commented on src/components/Divider/Divider.tsx
> +                content && 'after:content-["or"]'
please use divide from tailwind, and orDivider for or

2023-04-03 19:00 UTC, rikarsen commented on src/pages/profile/monitoring-systems/index.tsx
> +          <div className="mb-5 xl:w-[124px]">
use sm for small size and fl for full width

2023-04-06 00:59 UTC, ArthurO2002 approved these changes

2023-04-08 13:58 UTC, ArthurO2002 submitted a review, later dismissed

2023-04-10 15:31 UTC, ArthurO2002 submitted a review, later dismissed

2023-04-10 17:35 UTC, rikarsen approved these changes

2023-04-10 18:07 UTC, merged