FEATURE: Improve in login and register pages the UI
STA-Development/BEP_FE pull request #35
Opened 2023-04-11 14:23 UTC by DavMovsesyan2002

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-04-13 15:41 UTC, Arthur02V requested changes

2023-04-13 15:41 UTC, Arthur02V commented on src/pages/login/index.tsx
> +  }
onGoogleAuth

2023-04-13 15:41 UTC, Arthur02V commented on src/manager/authentication/authManager.ts
> +  },
googleSignIn

2023-04-13 15:58 UTC, ArthurO2002 requested changes
We should not send role on register

2023-04-13 15:59 UTC, ArthurO2002 commented
Let's add some validator package for example yup validator to not write custom error

2023-04-17 15:57 UTC, ArthurO2002 requested changes

2023-04-17 15:57 UTC, ArthurO2002 commented on src/pages/login/index.tsx
> +            // onClick={handleLogin}
remove comments

2023-04-17 15:57 UTC, ArthurO2002 commented on src/pages/reset-password/index.tsx
>        setEmailVerificationError('Email not recognized')
This is not needed anymore

2023-04-17 17:42 UTC, rikarsen requested changes
![image](https://user-images.githubusercontent.com/6823614/232566717-2c4756a0-cb03-4714-bd18-0338da0a880f.png)
![image](https://user-images.githubusercontent.com/6823614/232566765-5b6de605-6cb3-49f6-af00-328125b360cd.png)

Please review UI Dav jan. Many parts need to clean up and you have console errors

2023-04-18 16:54 UTC, ArthurO2002 submitted a review, later dismissed

2023-04-18 16:54 UTC, ArthurO2002 commented on src/pages/login/index.tsx
> +                className="ml-2	font-normal	"
Clear later

2023-04-18 17:03 UTC, rikarsen requested changes
fix width from 350px to 380px
add google logo to login with google button

2023-04-18 17:29 UTC, DavMovsesyan2002 commented on src/pages/login/index.tsx
> +  }
Done

2023-04-18 17:29 UTC, DavMovsesyan2002 commented on src/manager/authentication/authManager.ts
> +  },
Done

2023-04-19 17:05 UTC, merged