[BF-53] Feature/educational institute single
STA-Development/BEP_FE pull request #36
Opened 2023-04-11 15:40 UTC by SuroNorekyan

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-04-11 23:29 UTC, gor017 requested changes

2023-04-11 23:29 UTC, gor017 commented on src/components/IndividualCarousel/index.tsx
> +  const [currentIndex, setCurrentIndex] = useState(0)
Also, add type to this

2023-04-11 23:29 UTC, gor017 commented on src/pages/educational-institutes/[id].tsx
> +  }
I think we can check if id is truthy or falsy, and do all checking logic in the same return

2023-04-17 16:39 UTC, ArthurO2002 commented on src/components/EducationalInstitutesSingle/index.tsx
> +      />
Create maps reusable component, get the url from env and pass as prop

2023-04-17 16:40 UTC, ArthurO2002 commented on src/components/Icons/Toolbox.tsx
> +      <path d="M5 2.25293V3.00031H2.25C1.00736 3.00031 0 4.00766 0 5.2503V13.7471C0 14.9897 1.00736 15.9971 2.25 15.9971H17.75C18.9926 15.9971 20 14.9897 20 13.7471V5.25031C20 4.00766 18.9926 3.00031
Call the svg from svg file

2023-04-17 16:40 UTC, ArthurO2002 commented on src/components/Icons/PersonAccount.tsx
> +      fill="none"
Here too

2023-04-17 16:41 UTC, ArthurO2002 commented on src/components/IndividualCarousel/index.tsx
> +      console.log(carousel.current.offsetWidth)
remove lpg

2023-04-17 16:41 UTC, ArthurO2002 commented on src/components/IndividualCarousel/index.tsx
> +      carousel.current.offsetWidth * currentIndex <= maxScrollWidth.current
```suggestion
      carousel.current &&
      carousel.current.offsetWidth * currentIndex <= maxScrollWidth.current
```

2023-04-17 16:43 UTC, ArthurO2002 commented on src/components/IndividualCarousel/index.tsx
> +              src="/image1.jpg"
Use this instead of custom code
https://flowbite.com/docs/components/carousel/

2023-04-17 16:44 UTC, ArthurO2002 commented on src/pages/educational-institutes/[id].tsx
> +  const idString = Array.isArray(id) ? id[0].toString() : id?.toString()
Url can't be array in your case, make sure it's always string)

2023-04-17 16:45 UTC, ArthurO2002 commented on src/pages/educational-institutes/[id].tsx
> +  if (idString) {
Try to use inline conditions like `idString ? <Code></Code>`

2023-04-17 16:45 UTC, ArthurO2002 commented on src/pages/educational-institutes/index.tsx
> +      })
Use dispatch and move the logic to middleware

2023-04-17 16:45 UTC, ArthurO2002 commented on src/pages/educational-institutes/index.tsx
> +        console.log(error)
Remove log

2023-04-17 16:46 UTC, ArthurO2002 commented on src/pages/educational-institutes/index.tsx
> +  const emptyInstitutes = [0, 1, 2]
We don't need to keep this kind of constants

2023-04-17 16:46 UTC, ArthurO2002 commented on src/redux/slices/educational-institutes/initialState.ts
> +  page: '1',
```suggestion
  page: number,
```

2023-04-17 16:47 UTC, ArthurO2002 commented on src/redux/slices/educational-institutes/middleware.ts
> +    }
Wrong use of dispatch, see examples in project

2023-04-19 23:15 UTC, ArthurO2002 commented
Please pull from master

2023-04-25 23:36 UTC, ArthurO2002 commented
Sur jan please fix conflicts

2023-05-06 19:08 UTC, closed without merging