[BF-78] FEAT: Implement language selector UI and functionality
STA-Development/BEP_FE pull request #43
Opened 2023-04-18 06:07 UTC by gor017

### What are you trying to accomplish?
[BF-78]
### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?
<img width="307" alt="image" src="https://user-images.githubusercontent.com/85189675/232686065-5c2ce736-edd1-4195-b950-c0e143496a94.png">

2023-04-18 10:57 UTC, rikarsen requested changes
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6823614/232756947-47a3c8cc-edab-4dcf-b2e3-6a3c725a9edd.png">
you have errors

2023-04-19 07:13 UTC, gor017 commented
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/6823614/232756947-47a3c8cc-edab-4dcf-b2e3-6a3c725a9edd.png">
> 
> you have errors

Done

2023-04-19 20:09 UTC, ArthurO2002 requested changes

2023-04-19 20:09 UTC, ArthurO2002 commented on src/components/Icons/lang/EnIcon.tsx
> +export const EnIcon: FC<IconProps> = ({ fill = 'fill-[#212121]', className, ...rest }) => {
Should be color  from paleete

2023-04-19 20:09 UTC, ArthurO2002 commented on src/components/Icons/lang/RuIcon.tsx
> +export const RuIcon: FC<IconProps> = ({ fill = 'fill-[#212121]', className, ...rest }) => {
Here too

2023-04-19 20:09 UTC, ArthurO2002 commented on src/pages/_app.tsx
> +    }
```suggestion
    if (data) {
      dispatch(usersMiddleware.changeLanguage(data))
    }
```

2023-04-19 20:09 UTC, ArthurO2002 commented on src/redux/slices/users/middleware.ts
> +    dispatch(setError((error as IError).response.data.status.message))
Add ? to not brake the page

2023-04-19 21:17 UTC, vahea95 commented on src/redux/slices/users/middleware.ts
> +    dispatch(setError((error as IError).response.data.status.message))
done

2023-04-19 21:17 UTC, vahea95 commented on src/components/Icons/lang/RuIcon.tsx
> +export const RuIcon: FC<IconProps> = ({ fill = 'fill-[#212121]', className, ...rest }) => {
done

2023-04-19 21:17 UTC, vahea95 commented on src/components/Icons/lang/EnIcon.tsx
> +export const EnIcon: FC<IconProps> = ({ fill = 'fill-[#212121]', className, ...rest }) => {
done

2023-04-19 23:13 UTC, ArthurO2002 approved these changes

2023-04-19 23:14 UTC, merged