[BF-81] FEAT: Add English translations of the texts
STA-Development/BEP_FE pull request #53
Opened 2023-04-21 16:33 UTC by vahea95

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-04-21 20:23 UTC, ArthurO2002 requested changes

2023-04-21 20:23 UTC, ArthurO2002 commented on src/pages/events/index.tsx
>          paths={['Home', 'Events']}
```suggestion
        title={t(Translation.PAGE_EVENTS_MAIN_TITLE)}
        description={t(Translation.PAGE_EVENTS_MAIN_DESCRIPTION)}
        paths={['Home', 'Events']}
```

2023-04-25 10:46 UTC, rikarsen approved these changes

2023-04-25 12:00 UTC, vahea95 commented on src/pages/events/index.tsx
>          paths={['Home', 'Events']}
Done

2023-04-27 15:55 UTC, ArthurO2002 approved these changes

2023-04-27 15:55 UTC, merged