Feature/forgot password
STA-Development/BEP_FE pull request #55
Opened 2023-04-24 20:02 UTC by DavMovsesyan2002

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-04-25 10:48 UTC, rikarsen approved these changes

2023-04-25 10:49 UTC, rikarsen requested changes
![image](https://user-images.githubusercontent.com/6823614/234254942-01d3f915-6c22-420b-859e-da4d73da5cf6.png)

you have error in build

2023-04-28 17:08 UTC, VahMats submitted a review, later dismissed

2023-04-28 17:16 UTC, gor017 requested changes

2023-04-28 17:16 UTC, gor017 commented on src/pages/reset-password/request-password.tsx
> +        {t(Translation.PAGE_RESET_PASSWORD_BUTTON)}
let's add loading on the button, I suggest customize loading case in Button component

2023-04-28 17:16 UTC, gor017 commented on src/pages/reset-password/verify-otp.tsx
> +      </Button>
also add loading here

2023-05-01 16:20 UTC, gor017 submitted a review, later dismissed

2023-05-01 21:14 UTC, ArthurO2002 requested changes

2023-05-01 21:14 UTC, ArthurO2002 commented on src/components/IsLoading/index.tsx
> +  <div className="... mr-3 h-7 w-7 animate-spin">
... ????

2023-05-01 21:14 UTC, ArthurO2002 commented on src/pages/reset-password/index.tsx
> +    methods.clearErrors()
Why are we clearing errors, if there is no error they will disappear

2023-05-01 21:14 UTC, ArthurO2002 commented on src/pages/reset-password/index.tsx
> +        usersMiddleware.resetPassword({
It's wrong each button should do it's own job

2023-05-01 21:14 UTC, ArthurO2002 commented on src/pages/reset-password/verify-otp.tsx
> +        {isResetPasswordLoading ? <IsLoading /> : t(Translation.PAGE_VERIFY_OTP_BUTTON)}
Loading

2023-05-02 12:39 UTC, DavMovsesyan2002 commented on src/pages/register/index.tsx
> +              )}
Done

2023-05-02 18:05 UTC, ArthurO2002 requested changes
Button should have different loading and disabled states

2023-05-02 18:05 UTC, ArthurO2002 commented on src/manager/authentication/authManager.ts
> +      `http://localhost:2002/users/v1/auth/google`
Never keep this kind of hardcoded data

2023-05-03 21:51 UTC, merged