FEATURE: Improve redirection logic
STA-Development/BEP_FE pull request #92
Opened 2023-05-25 16:43 UTC by DavMovsesyan2002

### What are you trying to accomplish?

### What approach did you take and why?

### Elaborate any architectural decisions made

### What should reviewers focus on?

### Testing?

2023-05-25 16:53 UTC, ArthurO2002 requested changes

2023-05-25 16:53 UTC, ArthurO2002 commented on src/layouts/LayoutController.tsx
> +
File name should be middleware, it should define do user have access to that page or not

2023-05-26 15:17 UTC, ArthurO2002 requested changes

2023-05-26 15:17 UTC, ArthurO2002 commented on src/Middleware.tsx
> +      router.push('/')
Rename to publicRoutes and privateRoutes

2023-05-29 14:48 UTC, Arthur02V approved these changes

2023-05-29 14:58 UTC, merged